window.CARBON_MATERIALS = [
  {
    "priority": "P0",
    "rank": 1,
    "name": "单层聚合 C60 / 2D fullerene network",
    "route": "新碳相/曲率拓扑",
    "category": "纯碳",
    "sourceWeight": "Nature 主刊",
    "source": "https://www.nature.com/articles/s41586-022-04771-5",
    "novelty": 5,
    "evidence": 5,
    "transfer": 4,
    "access": 1,
    "blank": 5,
    "innovation": "C60 笼在二维平面内共价连接，形成有序拓扑、曲率和较高电子亲和性的纯碳骨架。",
    "hypothesis": "曲面 π 体系、笼-笼连接位点和中等带隙可能给 *OOH 弱吸附/定向吸附提供新窗口。",
    "experiment": "先用聚合 C60 薄膜、C60 衍生碳或 C60/导电碳复合物做可行性；真正单层样品适合合作获取。",
    "tests": "XRD/SAED；Raman/XPS；RRDE；H2O2 分解测试。",
    "risk": "样品制备和相纯度难度高；导电和比表面积可能限制电流。",
    "action": "先做小样/合作"
  },
  {
    "priority": "P0",
    "rank": 2,
    "name": "单层非晶碳 MAC",
    "route": "纯碳拓扑缺陷库",
    "category": "纯碳",
    "sourceWeight": "Nature 主刊",
    "source": "https://www.nature.com/articles/s41586-019-1871-2",
    "novelty": 5,
    "evidence": 5,
    "transfer": 5,
    "access": 2,
    "blank": 5,
    "innovation": "厘米级、自由支撑、三配位非晶碳；包含五/六/七/八元环分布，区别于简单缺陷石墨烯。",
    "hypothesis": "能把非六元环拓扑缺陷从 N/O/B 掺杂中分离出来，直接检验 5/7/8 元环与 2e ORR 的关系。",
    "experiment": "低温 CVD 非晶碳膜、离子/等离子体缺陷化石墨烯可作为替代路线。",
    "tests": "TEM/STEM 统计环结构；Raman D/G/2D；XPS 排除杂原子；EIS + RRDE。",
    "risk": "本征绝缘或低导电；需要导电底层或复合电极。",
    "action": "机制课题首选"
  },
  {
    "priority": "P0",
    "rank": 3,
    "name": "Biphenylene network / 4-6-8 非苯环碳",
    "route": "周期性非六元环",
    "category": "纯碳",
    "sourceWeight": "Science 主刊",
    "source": "https://www.science.org/doi/10.1126/science.abg4509",
    "novelty": 5,
    "evidence": 5,
    "transfer": 4,
    "access": 1,
    "blank": 5,
    "innovation": "由四、六、八元环组成的非苯型二维碳 allotrope，周期性地把 Stone-Wales 类缺陷变成晶格。",
    "hypothesis": "4/8 元环造成局域电荷与应变，可能调节 *OOH 结合并抑制 O-O 断裂。",
    "experiment": "先用含联苯/四苯结构前驱体热解，或 on-surface 合成样品做微电极验证。",
    "tests": "STM/TEM；Raman/UPS；与缺陷石墨烯、纳米孔石墨烯对照。",
    "risk": "UHV 表面合成难以放量；真实电极构筑困难。",
    "action": "结构启发优先"
  },
  {
    "priority": "P0",
    "rank": 4,
    "name": "γ-Graphyne / 多层 graphyne",
    "route": "sp-sp2 炔键碳",
    "category": "纯碳",
    "sourceWeight": "JACS / Nature Synthesis 相关路线",
    "source": "https://pubs.acs.org/doi/10.1021/jacs.2c13541",
    "novelty": 5,
    "evidence": 4,
    "transfer": 5,
    "access": 2,
    "blank": 4,
    "innovation": "苯环由炔键连接，形成均一 sp/sp2 碳和固有孔道；区别于 graphdiyne 的二炔桥。",
    "hypothesis": "sp 碳位点、电荷各向异性和亚纳米孔可能给 O2 端位吸附与 *OOH 脱附提供新组合。",
    "experiment": "优先合成多层/粉体 graphyne 或 graphdiyne-like 对照；比较 sp 碳比例。",
    "tests": "Raman 炔键峰；XPS C1s sp/sp2；BET/孔径；RRDE + peroxide titration。",
    "risk": "graphyne 合成路线存在争议，必须严控结构证据。",
    "action": "做，但严控表征"
  },
  {
    "priority": "P0",
    "rank": 5,
    "name": "沸石模板 3D graphene-like microporous carbon",
    "route": "纯碳周期微孔/三维骨架",
    "category": "纯碳",
    "sourceWeight": "Nature 主刊",
    "source": "https://www.nature.com/articles/nature18284",
    "novelty": 4,
    "evidence": 5,
    "transfer": 5,
    "access": 3,
    "blank": 4,
    "innovation": "在沸石孔道内形成类石墨烯碳，模板去除后得到三维周期微孔和较高导电性。",
    "hypothesis": "亚纳米微孔、曲率和三维导电网络可能增强 O2 富集并改变水/氧局部环境。",
    "experiment": "从 FAU/EMT/beta 沸石模板碳入手，优先做金属残留去除与空白对照。",
    "tests": "ICP；N2/CO2 吸附；RDE/RRDE；H2O2 稳定性。",
    "risk": "金属催化剂残留会混淆机理；孔过窄可能传质受限。",
    "action": "高可行性首选"
  },
  {
    "priority": "P0",
    "rank": 6,
    "name": "Bottom-up nanoporous graphene / 碳纳米孔阵列",
    "route": "原子精确孔/边缘",
    "category": "纯碳",
    "sourceWeight": "Science 主刊",
    "source": "https://doi.org/10.1126/science.aar2009",
    "novelty": 5,
    "evidence": 5,
    "transfer": 5,
    "access": 2,
    "blank": 5,
    "innovation": "分子前驱体自下而上形成有序纳米孔石墨烯，孔径、密度和边缘结构由前驱体决定。",
    "hypothesis": "二电子 ORR 对边缘/孔口位点敏感，可把边缘密度和孔限域作为独立变量。",
    "experiment": "无法获得原子级样品时，用孔径可控 holey graphene/graphene nanomesh 做放大版。",
    "tests": "孔径 TEM/AFM；边缘含氧量 XPS；RRDE 选择性 vs 孔径/边缘密度。",
    "risk": "表面合成样品面积小；粉体替代品结构不够精确。",
    "action": "非常值得设为主线"
  },
  {
    "priority": "P0",
    "rank": 7,
    "name": "Atomically precise graphene nanoribbons",
    "route": "边缘拓扑工程",
    "category": "纯碳",
    "sourceWeight": "Science / Nature 系",
    "source": "https://www.science.org/doi/10.1126/science.abb8880",
    "novelty": 4,
    "evidence": 5,
    "transfer": 4,
    "access": 2,
    "blank": 4,
    "innovation": "通过分子前驱体控制扶手椅、锯齿、cove 等边缘结构；边缘态可被精确调节。",
    "hypothesis": "可把 armchair/zigzag/cove 边缘对 *OOH 结合的影响做成结构-性能关系。",
    "experiment": "采购或合成 bottom-up GNR 粉体/膜；用 CNT/graphene 作导电骨架负载。",
    "tests": "AFM/TEM；Raman 边缘峰；XPS 氧化态；边缘密度归一化活性。",
    "risk": "产量有限；边缘在电解液中可能氧化重构。",
    "action": "机制对照优先"
  },
  {
    "priority": "P0",
    "rank": 8,
    "name": "Benzene-derived carbon nanothreads",
    "route": "一维 sp3 碳纳米材料",
    "category": "C-H 端基碳",
    "sourceWeight": "Nature Materials",
    "source": "https://www.nature.com/articles/nmat4088",
    "novelty": 4,
    "evidence": 5,
    "transfer": 2,
    "access": 1,
    "blank": 5,
    "innovation": "高压固相聚合苯得到亚纳米 sp3 碳线束，属于有序 sp3 低维碳路线。",
    "hypothesis": "sp3/应变/端基会改变 O2 与水界面，适合作为复合电极中的结构添加物。",
    "experiment": "不建议直接作为主催化剂；可用 sp3-rich carbon film 替代验证。",
    "tests": "固态 NMR/Raman；导电性；RRDE 低负载筛选。",
    "risk": "高压合成和导电性是主要瓶颈。",
    "action": "远期探索"
  },
  {
    "priority": "P0",
    "rank": 9,
    "name": "Diamane / fluorinated single-layer diamond",
    "route": "二维 sp3 转换",
    "category": "表面终止碳",
    "sourceWeight": "Nature Nanotechnology",
    "source": "https://www.nature.com/articles/s41565-019-0582-z",
    "novelty": 4,
    "evidence": 4,
    "transfer": 3,
    "access": 1,
    "blank": 5,
    "innovation": "双层石墨烯经氟化诱导层间 C-C 键，转变为单层类金刚石结构。",
    "hypothesis": "sp2 到 sp3 的相变和 F 端基可构建高度极化界面，检验 sp3 碳/表面终止效应。",
    "experiment": "先用 BDD、氟化石墨烯、氢化石墨烯作为可行替代；真正 diamane 适合微区电化学。",
    "tests": "XPS F/C 与 sp3；Raman；导电性；H2O2 生成和分解双测。",
    "risk": "绝缘性强；F 端基可能脱落或引发副反应。",
    "action": "替代模型先行"
  },
  {
    "priority": "P1",
    "rank": 10,
    "name": "边缘富集 3D fuzzy graphene / 竖直边缘石墨烯",
    "route": "纯碳边缘工程",
    "category": "纯碳/轻微含氧",
    "sourceWeight": "高评价催化文献/预印本线索",
    "source": "https://arxiv.org/abs/1904.04946",
    "novelty": 4,
    "evidence": 3,
    "transfer": 5,
    "access": 4,
    "blank": 3,
    "innovation": "纳米线模板生成大量出平面石墨烯边缘，可把边缘密度作为可调参数。",
    "hypothesis": "边缘和 C=O/C-OH 位点可能是 2e ORR 的核心活性因素之一。",
    "experiment": "复现纳米线模板或用商用垂直石墨烯；设定边缘密度梯度。",
    "tests": "边缘密度定量；XPS C=O/C-OH；RRDE collection efficiency；TOF 归一化。",
    "risk": "不够新，但很适合验证机制。",
    "action": "近期可立即做"
  },
  {
    "priority": "P1",
    "rank": 11,
    "name": "Laser-induced graphene / LIG",
    "route": "快速制备缺陷多孔碳",
    "category": "纯碳/可控含氧",
    "sourceWeight": "Science Advances / ACS 系",
    "source": "https://www.science.org/doi/10.1126/sciadv.1500736",
    "novelty": 3,
    "evidence": 3,
    "transfer": 4,
    "access": 5,
    "blank": 3,
    "innovation": "激光把聚合物、木材、PI、CO2 前驱体转为多孔导电石墨烯网络，可做图案化电极。",
    "hypothesis": "激光功率、气氛、前驱体可调控边缘、孔、含氧基团和疏水性。",
    "experiment": "用 PI/Lignin/biomass-LIG 做参数矩阵；直接作为 GDE 或碳纸涂层。",
    "tests": "Raman 缺陷；XPS O/C；接触角；ECSA；RRDE 或流动电解槽。",
    "risk": "结构不够原子级；批间差异要控制。",
    "action": "适合快速筛选"
  },
  {
    "priority": "P1",
    "rank": 12,
    "name": "Carbon nano-onions / fullerene-like curved carbon",
    "route": "曲率/多壳层 sp2",
    "category": "纯碳",
    "sourceWeight": "Carbon / ACS Nano 等",
    "source": "https://pubs.acs.org/doi/10.1021/nn9010976",
    "novelty": 3,
    "evidence": 3,
    "transfer": 4,
    "access": 4,
    "blank": 4,
    "innovation": "多壳层类富勒烯碳，曲率、五元环和层间间隙丰富，粉体可获得。",
    "hypothesis": "曲率和五元环可能弱化 *OOH 或抑制 O-O 断裂，是 2D C60 的低门槛替代模型。",
    "experiment": "采购 CNO，做热退火/臭氧/电化学氧化系列；与碳黑、CNT 对照。",
    "tests": "TEM 壳层；Raman；XPS；H2O2 生成/分解；疏水性。",
    "risk": "商业样品杂质和粒径差异大。",
    "action": "低成本探索"
  },
  {
    "priority": "P1",
    "rank": 13,
    "name": "Nanodiamond-derived graphene / sp2-sp3 hybrid carbon",
    "route": "sp2/sp3 界面",
    "category": "纯碳",
    "sourceWeight": "Nature/ACS/Carbon 文献线索",
    "source": "检索线索：nanodiamond-derived graphene sp2/sp3 hybrid carbon electrocatalysis",
    "novelty": 3,
    "evidence": 4,
    "transfer": 4,
    "access": 4,
    "blank": 4,
    "innovation": "以纳米金刚石退火或表面重构得到 sp2 壳/sp3 核，形成大量碳-碳相界面。",
    "hypothesis": "sp2 导电壳 + sp3 极化核/边界可能改变 O2 吸附和 H2O2 脱附。",
    "experiment": "用商用纳米金刚石、爆轰纳米金刚石和退火样品做系列；重点控制表面氧。",
    "tests": "XRD/Raman 判定 sp2/sp3；TEM 核壳；XPS/O2-TPD；RRDE。",
    "risk": "表面官能团而非 sp2/sp3 界面可能是真实活性来源。",
    "action": "建议做对照库"
  },
  {
    "priority": "P1",
    "rank": 14,
    "name": "Graphene aerogel / 3D porous graphene monolith",
    "route": "三维导电孔网络",
    "category": "纯碳/轻微含氧",
    "sourceWeight": "Nature Materials / Adv. Mater. 文献线索",
    "source": "检索线索：graphene aerogel 3D porous graphene monolith oxygen reduction gas diffusion electrode",
    "novelty": 3,
    "evidence": 4,
    "transfer": 4,
    "access": 4,
    "blank": 3,
    "innovation": "宏观自支撑、低密度、高孔隙率石墨烯网络，可减少粘结剂影响。",
    "hypothesis": "气体扩散和导电网络对 H2O2 电合成很关键，可把材料创新与电极结构耦合。",
    "experiment": "使用还原氧化石墨烯气凝胶、冷冻干燥/水热路线；做疏水处理与孔结构调控。",
    "tests": "N2/Hg 孔结构；SEM；接触角；流动池产率。",
    "risk": "本征活性未必强，容易变成电极工程课题。",
    "action": "适合放大验证"
  },
  {
    "priority": "P2",
    "rank": 15,
    "name": "氧官能团可控碳：醌/羰基/内酯/醚",
    "route": "非金属官能化",
    "category": "O 掺杂/表面氧",
    "sourceWeight": "JACS/ACS Catalysis/高引文 ORR 文献",
    "source": "https://arxiv.org/abs/1904.04946",
    "novelty": 3,
    "evidence": 3,
    "transfer": 5,
    "access": 5,
    "blank": 2,
    "innovation": "通过温和氧化、等离子体或电化学活化定向引入 C=O、C-OH、COOH 等位点。",
    "hypothesis": "许多证据指向边缘 C=O/C-OH 对 *OOH 选择性有利，是 2e ORR 强基准。",
    "experiment": "所有新材料都配氧化/还原处理，区分结构效应和氧官能团效应。",
    "tests": "XPS 分峰；Boehm 滴定；原位 Raman/ATR-SEIRAS；RRDE + 滴定。",
    "risk": "太常见，创新性主要来自精准调控。",
    "action": "必备基准"
  },
  {
    "priority": "P2",
    "rank": 16,
    "name": "B / B-O 掺杂石墨烯、CNT、porous carbon",
    "route": "非金属电子调控",
    "category": "B 掺杂",
    "sourceWeight": "ACS Energy Lett./Adv. Mater./JACS 文献线索",
    "source": "检索线索：B-doped carbon graphene two-electron oxygen reduction hydrogen peroxide",
    "novelty": 3,
    "evidence": 3,
    "transfer": 4,
    "access": 4,
    "blank": 3,
    "innovation": "B 提供缺电子位点，改变相邻 C 的电荷和 O2/*OOH 吸附。",
    "hypothesis": "B 位点可能促进 O2 端位吸附；与 O 官能团协同可能提高 2e 选择性。",
    "experiment": "用硼酸/硼烷/BCN 前驱体热解；做 B-only、B/O、B/N 三组。",
    "tests": "XPS B-C/B-O；ICP；RRDE；H2O2 分解测试。",
    "risk": "B-N-C 容易转向 4e ORR；B 含量与真实活性位点需分离。",
    "action": "中高优先级"
  },
  {
    "priority": "P2",
    "rank": 17,
    "name": "F / CFx / 氟化石墨烯衍生碳",
    "route": "界面疏水与极化",
    "category": "F 掺杂/终止",
    "sourceWeight": "Nature Nanotech / ACS Materials",
    "source": "https://www.nature.com/articles/s41565-019-0582-z",
    "novelty": 3,
    "evidence": 4,
    "transfer": 4,
    "access": 3,
    "blank": 4,
    "innovation": "C-F 键调节碳表面极性、疏水性和电荷分布，也可通过退火形成缺陷。",
    "hypothesis": "适度疏水 + 极化 C 可能提升 H2O2 脱附，并改变局部 O2/H2O 活度。",
    "experiment": "从氟化石墨烯/CFx 温和退火系列做起，避免过度绝缘。",
    "tests": "XPS C-F；接触角；电导；RRDE；F 流失检测。",
    "risk": "导电性下降和 F 稳定性风险高。",
    "action": "界面变量"
  },
  {
    "priority": "P2",
    "rank": 18,
    "name": "P/S/Se 单掺或共掺碳",
    "route": "非金属极化/自旋调控",
    "category": "P/S/Se 掺杂",
    "sourceWeight": "Adv. Energy Mater./ACS Catalysis 文献线索",
    "source": "检索线索：P S Se doped carbon two-electron ORR hydrogen peroxide electrosynthesis",
    "novelty": 3,
    "evidence": 3,
    "transfer": 4,
    "access": 4,
    "blank": 3,
    "innovation": "大半径杂原子造成局部应变、电荷极化和疏水性变化；可与 O 官能团耦合。",
    "hypothesis": "S/Se/P 周围 C 可能形成弱吸附位点，共掺可调 *OOH 结合能和水化环境。",
    "experiment": "用含 P/S/Se 有机盐或生物质前驱体热解；做单掺和共掺矩阵。",
    "tests": "XPS 化学态；元素分析；接触角；RRDE；稳定性。",
    "risk": "杂原子种类多，机理容易发散。",
    "action": "矩阵筛选"
  },
  {
    "priority": "P2",
    "rank": 19,
    "name": "C2N / crystalline carbon nitride holey 2D framework",
    "route": "N 掺杂孔阵列",
    "category": "C-N 骨架",
    "sourceWeight": "Nature Communications",
    "source": "https://www.nature.com/articles/ncomms7486",
    "novelty": 4,
    "evidence": 4,
    "transfer": 4,
    "access": 2,
    "blank": 4,
    "innovation": "二维 C2N-h2D 晶体具有周期性孔和吡啶 N 位点，不是普通 g-C3N4。",
    "hypothesis": "周期孔 + 吡啶 N 可同时调节 O2 吸附和质子转移。",
    "experiment": "合成 C2N 或用含三嗪/吡啶 COF 热解得到近似孔阵列碳。",
    "tests": "FTIR/XPS N 型；TEM 孔结构；电导；RRDE；对照 g-C3N4。",
    "risk": "电导低；N 位点可能促进 4e 或副反应。",
    "action": "N 掺杂高端路线"
  },
  {
    "priority": "P2",
    "rank": 20,
    "name": "金属单原子低 4e 倾向：Zn/Sn/Bi-N-C 等",
    "route": "金属掺杂但弱 O-O 断裂",
    "category": "单原子金属-N-C",
    "sourceWeight": "Nature Catalysis/JACS/ACS Catalysis 文献线索",
    "source": "检索线索：Zn-N-C Sn-N-C Bi-N-C single atom catalyst two-electron ORR hydrogen peroxide",
    "novelty": 3,
    "evidence": 4,
    "transfer": 3,
    "access": 3,
    "blank": 3,
    "innovation": "选择 redox-inactive 或 p-block 金属中心，避免 Fe/Co 强 4e ORR。",
    "hypothesis": "单原子位点可增强 O2 活化，但必须避免 O-O 键断裂和 H2O2 分解。",
    "experiment": "做 Zn-N-C、Sn-N-C 和 metal-free N-C 对照；必须测 H2O2。",
    "tests": "XAS/HAADF-STEM；ICP；RRDE；K-L；Fenton/分解测试。",
    "risk": "金属位点可能分解 H2O2 或转 4e。",
    "action": "谨慎做"
  },
  {
    "priority": "P2",
    "rank": 21,
    "name": "高熵非金属共掺碳 B/N/O/F/S",
    "route": "多位点协同/局域熵",
    "category": "多非金属掺杂",
    "sourceWeight": "新兴高熵材料 + 碳催化文献线索",
    "source": "检索线索：high-entropy heteroatom-doped carbon B N O F S oxygen reduction hydrogen peroxide",
    "novelty": 4,
    "evidence": 4,
    "transfer": 4,
    "access": 3,
    "blank": 4,
    "innovation": "利用多种非金属和缺陷组合形成宽分布吸附能，筛出接近 2e ORR 火山顶的位点。",
    "hypothesis": "用吸附能分布提升选择窗口；适合高通量筛选。",
    "experiment": "同一碳骨架做 B/N/O/F/S 逐步添加；结合 DFT 或机器学习筛选。",
    "tests": "XPS/ToF-SIMS；元素映射；RRDE；选择性分布与稳定性。",
    "risk": "机理复杂；容易被质疑黑箱材料。",
    "action": "高通量副线"
  },
  {
    "priority": "P3",
    "rank": 22,
    "name": "Graphene / h-BN in-plane 或垂直异质结",
    "route": "碳-绝缘极性界面",
    "category": "C/BN 异质结",
    "sourceWeight": "Nature Materials/Nature Nanotech",
    "source": "https://www.nature.com/articles/nmat4349",
    "novelty": 3,
    "evidence": 4,
    "transfer": 3,
    "access": 2,
    "blank": 4,
    "innovation": "石墨烯导电网络与 h-BN 极性 B-N 键形成边界界面，边界 C/B/N 位点可调。",
    "hypothesis": "C-B/N 边界可能改变 O2 吸附与质子转移，h-BN 调节局部疏水/绝缘界面。",
    "experiment": "先用 graphene + BN nanosheets 物理混合/热处理，再探索 in-plane C-BN。",
    "tests": "TEM/EELS 边界；XPS B/N；电导；RRDE。",
    "risk": "BN 绝缘；界面比例难定量。",
    "action": "异质结低优先"
  },
  {
    "priority": "P3",
    "rank": 23,
    "name": "Graphene / black phosphorus 或 phosphorene-carbon",
    "route": "碳-磷二维界面",
    "category": "C/P 异质结",
    "sourceWeight": "Nature Nanotech/Adv. Mater.",
    "source": "https://www.nature.com/articles/nnano.2014.257",
    "novelty": 3,
    "evidence": 4,
    "transfer": 3,
    "access": 2,
    "blank": 4,
    "innovation": "磷烯提供高极化 P 位点，石墨烯提供导电与稳定支撑。",
    "hypothesis": "P 位点可能改变 O2 和 *OOH 吸附；碳层可保护磷烯并提供电子通道。",
    "experiment": "优先做少层 BP/CNT 或 BP/graphene 低负载；严格测试 H2O2 分解。",
    "tests": "Raman BP；XPS P oxidation；RRDE；长期稳定性。",
    "risk": "BP 氧化严重；P 位点可能产生副反应。",
    "action": "探索性低优先"
  },
  {
    "priority": "P3",
    "rank": 24,
    "name": "MXene / carbon hybrid",
    "route": "导电二维异质界面",
    "category": "碳/MXene",
    "sourceWeight": "Nature Reviews Materials/ACS Nano",
    "source": "https://www.nature.com/articles/natrevmats201698",
    "novelty": 3,
    "evidence": 4,
    "transfer": 2,
    "access": 3,
    "blank": 3,
    "innovation": "MXene 提供亲水导电片层，碳材料提供疏水/稳定结构，可构造多尺度通道。",
    "hypothesis": "更偏电极结构：调 O2、水和离子传输；Ti 位点过强会分解 H2O2。",
    "experiment": "把 MXene 低比例引入碳气凝胶/碳纸，优先做传质和稳定性对照。",
    "tests": "XPS Ti oxidation；接触角；RRDE；H2O2 分解；流动池。",
    "risk": "金属氧化位点可能消耗 H2O2。",
    "action": "工程对照"
  },
  {
    "priority": "P3",
    "rank": 25,
    "name": "Carbon quantum dots / graphene quantum dots on CNT/graphene",
    "route": "尺寸/边缘/荧光碳点",
    "category": "碳点-碳复合",
    "sourceWeight": "Nature Communications/ACS Nano",
    "source": "https://www.nature.com/articles/ncomms1798",
    "novelty": 3,
    "evidence": 3,
    "transfer": 4,
    "access": 4,
    "blank": 3,
    "innovation": "碳点具有大量边缘和官能团，可负载在 CNT/graphene 上提高导电与可回收性。",
    "hypothesis": "量子尺寸、边缘和表面官能团可调，适合作为边缘/氧官能团可溶模型。",
    "experiment": "合成 N-free、O-rich、B-doped 三类碳点并负载 CNT。",
    "tests": "TEM/PL/XPS；zeta；RRDE；流失检测。",
    "risk": "碳点可能溶出；真实活性来源难界定。",
    "action": "快速变量库"
  },
  {
    "priority": "P3",
    "rank": 26,
    "name": "BDD / boron-doped diamond electrode",
    "route": "产品化 sp3 碳电极",
    "category": "B 掺杂金刚石",
    "sourceWeight": "行业产品 + 电化学文献",
    "source": "https://www.condias.de/en/products/boron-doped-diamond-electrodes/",
    "novelty": 3,
    "evidence": 3,
    "transfer": 3,
    "access": 4,
    "blank": 2,
    "innovation": "商业化导电金刚石薄膜，电化学窗口宽、耐腐蚀。",
    "hypothesis": "可作为 sp3/B 掺杂碳和高稳定电极的工程对照。",
    "experiment": "购买 BDD 片，与玻碳/碳纸/石墨对照。",
    "tests": "B 掺杂浓度；表面终止 O/H；RRDE 或流动池。",
    "risk": "成本高；活性可能主要来自表面终止。",
    "action": "基准/工程对照"
  },
  {
    "priority": "P3",
    "rank": 27,
    "name": "商用 graphene nanotubes / SWCNT 网络",
    "route": "可放大导电骨架",
    "category": "纯碳产品",
    "sourceWeight": "公司产品/产业材料",
    "source": "https://ocsial.com/tuball/",
    "novelty": 2,
    "evidence": 2,
    "transfer": 3,
    "access": 5,
    "blank": 2,
    "innovation": "高长径比 CNT/graphene nanotubes 可低添加量构建导电网络和气体通道。",
    "hypothesis": "本征创新不高，但作为新碳相和掺杂碳的导电骨架很有价值。",
    "experiment": "采购 OCSiAl/TUBALL 或同类 SWCNT；酸洗/退火/氧化系列。",
    "tests": "TEM；Raman ID/IG；金属残留 ICP；RRDE。",
    "risk": "金属催化剂残留、纯度和批次差异会影响结果。",
    "action": "导电骨架/对照"
  },
  {
    "priority": "P3",
    "rank": 28,
    "name": "商用 graphene nanoplatelets / PureGRAPH / NanoXplore",
    "route": "可获得碳材料库",
    "category": "纯碳产品",
    "sourceWeight": "公司产品/产业材料",
    "source": "https://firstgraphene.net/products/puregraph/ ; https://nanoxplore.ca/products/",
    "novelty": 2,
    "evidence": 2,
    "transfer": 3,
    "access": 5,
    "blank": 2,
    "innovation": "大批量石墨烯片、纳米片或复合级 graphene，适合做筛选基准和放大验证。",
    "hypothesis": "作为可放大、可购买材料库，帮助判断高端结构是否真的优于产业级碳。",
    "experiment": "购买不同片径/层数/氧含量样品；统一电极制备和归一化指标。",
    "tests": "BET；Raman；XPS；粒径；RRDE；成本/性能。",
    "risk": "创新性低，但非常适合产业化对照。",
    "action": "必要对照"
  },
  {
    "priority": "P3",
    "rank": 29,
    "name": "AvCarb / 碳纸 / GDL 结构电极",
    "route": "电极结构产品",
    "category": "碳基产品",
    "sourceWeight": "公司产品/工程材料",
    "source": "https://www.avcarb.com/products/",
    "novelty": 2,
    "evidence": 2,
    "transfer": 4,
    "access": 5,
    "blank": 1,
    "innovation": "碳纸、碳布和气体扩散层可直接承载催化剂并控制 O2 传质。",
    "hypothesis": "二电子 ORR 很吃电极结构，同一催化剂在玻碳和 GDE 上可能完全不同。",
    "experiment": "把 P0/P1 材料加载在 GDL 上做流动池；与玻碳 RRDE 形成两级筛选。",
    "tests": "孔结构；疏水层；负载量；H2O2 产率/法拉第效率。",
    "risk": "不是催化剂创新，但会决定放大表现。",
    "action": "工程验证必备"
  },
  {
    "priority": "P0",
    "rank": 30,
    "name": "体相六方金刚石 / bulk lonsdaleite",
    "route": "纯碳 sp3 六方相",
    "category": "纯碳新相",
    "sourceWeight": "Nature 主刊",
    "source": "https://www.nature.com/search?q=%22Bulk%20hexagonal%20diamond%22",
    "novelty": 5,
    "evidence": 5,
    "transfer": 3,
    "access": 1,
    "blank": 5,
    "innovation": "从石墨经高压高温路线获得体相、高纯六方金刚石，区别于以往微量夹杂或冲击产物。",
    "hypothesis": "sp3 碳的六方堆垛、棱边/晶面终止和缺陷可作为极端疏水稳定碳相，帮助区分 sp2 边缘位点与 sp3 终止位点对 2e ORR 的贡献。",
    "experiment": "优先寻找合作或微晶粉体；若难获得，先用纳米金刚石/BDD/氧终止金刚石构建 sp3 对照组。",
    "tests": "XRD/Raman 区分 cubic diamond 与 lonsdaleite；XPS 表面终止；接触角；RRDE 与 H2O2 分解测试。",
    "risk": "样品可得性和导电性是主要瓶颈；可能更适合作为机理对照而非直接高电流催化剂。",
    "action": "联系样品/做 sp3 对照"
  },
  {
    "priority": "P1",
    "rank": 31,
    "name": "半-Mobius 碳环 / half-Mobius cyclocarbon topology",
    "route": "sp 碳环拓扑缺陷",
    "category": "纯碳拓扑分子",
    "sourceWeight": "Science 主刊 + 实验室新闻",
    "source": "https://www.chem.ox.ac.uk/article/a-molecule-with-half-mobius-topology",
    "novelty": 5,
    "evidence": 4,
    "transfer": 2,
    "access": 1,
    "blank": 5,
    "innovation": "以原子级可视化的扭转碳环实现半-Mobius 电子/几何拓扑，为 sp 碳、曲率和拓扑应变提供新的结构母题。",
    "hypothesis": "扭转 sp 碳链的局域曲率和端基诱导电荷可能改变 O2 端位吸附；可启发 graphyne/cyclocarbon-like 边缘缺陷设计。",
    "experiment": "不直接作为粉体催化剂；用于设计含炔键、扭曲孔口或环状 sp/sp2 边缘的前驱体碳化路线。",
    "tests": "合成替代材料需用 Raman 炔键峰、XPS sp/sp2、孔口尺寸与 RRDE 关联；优先和 graphyne 对照。",
    "risk": "单分子 UHV 体系难转化为电极材料；端基/基底效应可能主导性质。",
    "action": "作为拓扑启发候选"
  },
  {
    "priority": "P3",
    "rank": 32,
    "name": "Biofilm-disrupting and redox-active carbon dots modulate Wnt/β-catenin signaling to resolve a...",
    "route": "碳基异质结/复合结构",
    "category": "碳基复合",
    "sourceWeight": "Journal of Materials Science &amp; Technology / 顶刊子刊",
    "source": "https://doi.org/10.1016/j.jmst.2026.05.043",
    "novelty": 3,
    "evidence": 4,
    "transfer": 3,
    "access": 3,
    "blank": 3,
    "innovation": "云端自动检索到的高权重来源候选。题名指向 碳基异质结/复合结构，建议优先核查结构表征与合成可重复性。",
    "hypothesis": "异质界面可能改变电子传输、局部亲疏水性和 O2 传质，更适合作为工程放大或对照方向。",
    "experiment": "先按原文路线确认样品可得性；若样品难获取，寻找同结构低门槛替代模型并进行 RRDE 快速筛选。",
    "tests": "XPS/Raman/TEM/BET 或原文关键结构证据；RRDE；H2O2 化学定量；H2O2 分解/歧化测试。",
    "risk": "该条目由自动检索加入，进入正式实验前需要人工复核全文、样品纯度和二电子 ORR 相关性。",
    "action": "自动新增，人工复核"
  },
  {
    "priority": "P2",
    "rank": 33,
    "name": "Dual role of carbon nonstoichiometry in tuning dislocation behavior in high-entropy transitio...",
    "route": "掺杂碳/单原子调控",
    "category": "掺杂碳",
    "sourceWeight": "Journal of Materials Science &amp; Technology / 顶刊子刊",
    "source": "https://doi.org/10.1016/j.jmst.2026.06.012",
    "novelty": 3,
    "evidence": 4,
    "transfer": 3,
    "access": 3,
    "blank": 3,
    "innovation": "云端自动检索到的高权重来源候选。题名指向 掺杂碳/单原子调控，建议优先核查结构表征与合成可重复性。",
    "hypothesis": "杂原子或单原子位点可调节邻近碳电荷和 *OOH 结合能，但需重点排查 4e ORR 与 H2O2 分解副作用。",
    "experiment": "先按原文路线确认样品可得性；若样品难获取，寻找同结构低门槛替代模型并进行 RRDE 快速筛选。",
    "tests": "XPS/Raman/TEM/BET 或原文关键结构证据；RRDE；H2O2 化学定量；H2O2 分解/歧化测试。",
    "risk": "该条目由自动检索加入，进入正式实验前需要人工复核全文、样品纯度和二电子 ORR 相关性。",
    "action": "自动新增，人工复核"
  }
];

window.CARBON_FEED_META = {
  "cadence": "每 30 分钟",
  "updatedAt": "2026-07-02 21:48 Asia/Shanghai",
  "sourcePolicy": "三大顶刊、三大顶刊子刊、Nature Index 来源、高评价材料/催化期刊、先进实验室新闻、科学报道和前沿碳材料公司产品",
  "lastRunSummary": "自动新增 2 个候选：Biofilm-disrupting and redox-active carbon dots modulate Wnt/β-catenin signaling to resolve a...；Dual role of carbon nonstoichiometry in tuning dislocation behavior in high-entropy transitio..."
};

window.CARBON_SOURCE_DETAILS = {
  "单层聚合 C60 / 2D fullerene network": {
    "kind": "文献",
    "venue": "Nature",
    "year": "2022",
    "title": "Synthesis of a monolayer fullerene network",
    "link": "https://www.nature.com/articles/s41586-022-04771-5"
  },
  "单层非晶碳 MAC": {
    "kind": "文献",
    "venue": "Nature",
    "year": "2019",
    "title": "Synthesis and properties of free-standing monolayer amorphous carbon",
    "link": "https://www.nature.com/articles/s41586-019-1871-2"
  },
  "Biphenylene network / 4-6-8 非苯环碳": {
    "kind": "文献",
    "venue": "Science",
    "year": "2021",
    "title": "Biphenylene network: A nonbenzenoid carbon allotrope",
    "link": "https://www.science.org/doi/10.1126/science.abg4509"
  },
  "γ-Graphyne / 多层 graphyne": {
    "kind": "文献",
    "venue": "Journal of the American Chemical Society",
    "year": "2023",
    "title": "Scalable Synthesis and Characterization of Multilayer γ-Graphyne, New Carbon Crystals with a Small Direct Band Gap",
    "link": "https://pubs.acs.org/doi/10.1021/jacs.2c13541"
  },
  "沸石模板 3D graphene-like microporous carbon": {
    "kind": "文献",
    "venue": "Nature",
    "year": "2016",
    "title": "Lanthanum-catalysed synthesis of microporous 3D graphene-like carbons in a zeolite template",
    "link": "https://www.nature.com/articles/nature18284"
  },
  "Bottom-up nanoporous graphene / 碳纳米孔阵列": {
    "kind": "文献",
    "venue": "Science",
    "year": "2018",
    "title": "Bottom-up synthesis of multifunctional nanoporous graphene",
    "link": "https://doi.org/10.1126/science.aar2009"
  },
  "Atomically precise graphene nanoribbons": {
    "kind": "文献",
    "venue": "Science",
    "year": "2020",
    "title": "Rational synthesis of atomically precise graphene nanoribbons directly on metal oxide surfaces",
    "link": "https://www.science.org/doi/10.1126/science.abb8880"
  },
  "Benzene-derived carbon nanothreads": {
    "kind": "文献",
    "venue": "Nature Materials",
    "year": "2015",
    "title": "Benzene-derived carbon nanothreads",
    "link": "https://www.nature.com/articles/nmat4088"
  },
  "Diamane / fluorinated single-layer diamond": {
    "kind": "文献",
    "venue": "Nature Nanotechnology",
    "year": "2020",
    "title": "Chemically induced transformation of CVD bilayer graphene into fluorinated single-layer diamond",
    "link": "https://www.nature.com/articles/s41565-019-0582-z"
  },
  "边缘富集 3D fuzzy graphene / 竖直边缘石墨烯": {
    "kind": "预印本/文献线索",
    "venue": "arXiv",
    "year": "2019",
    "title": "Engineering Three-Dimensional Out-of-Plane Graphene Edge Sites for Highly Selective Two-Electron Oxygen Reduction Electrocatalysis",
    "link": "https://arxiv.org/abs/1904.04946"
  },
  "Laser-induced graphene / LIG": {
    "kind": "文献",
    "venue": "Science Advances",
    "year": "2015",
    "title": "Laser-induced graphene",
    "link": "https://www.science.org/doi/10.1126/sciadv.1500736"
  },
  "Carbon nano-onions / fullerene-like curved carbon": {
    "kind": "文献线索",
    "venue": "ACS Nano",
    "year": "2009",
    "title": "Carbon nano-onions / fullerene-like curved carbon article linked by DOI",
    "link": "https://pubs.acs.org/doi/10.1021/nn9010976"
  },
  "Nanodiamond-derived graphene / sp2-sp3 hybrid carbon": {
    "kind": "文献线索",
    "venue": "Nature / ACS / Carbon 等",
    "year": "近年",
    "title": "nanodiamond-derived graphene; sp2/sp3 hybrid carbon electrocatalysis",
    "link": ""
  },
  "Graphene aerogel / 3D porous graphene monolith": {
    "kind": "文献线索",
    "venue": "Nature Materials / Advanced Materials 等",
    "year": "近年",
    "title": "graphene aerogel; 3D porous graphene monolith; gas diffusion electrode",
    "link": ""
  },
  "氧官能团可控碳：醌/羰基/内酯/醚": {
    "kind": "文献/机制线索",
    "venue": "JACS / ACS Catalysis / arXiv 等",
    "year": "2019 起",
    "title": "oxygen functional groups and edge sites for two-electron oxygen reduction",
    "link": "https://arxiv.org/abs/1904.04946"
  },
  "B / B-O 掺杂石墨烯、CNT、porous carbon": {
    "kind": "文献线索",
    "venue": "ACS Energy Letters / Advanced Materials / JACS 等",
    "year": "近年",
    "title": "B-doped carbon / B-O carbon for two-electron oxygen reduction and H2O2 electrosynthesis",
    "link": ""
  },
  "F / CFx / 氟化石墨烯衍生碳": {
    "kind": "文献线索",
    "venue": "Nature Nanotechnology / ACS Materials 等",
    "year": "2020 起",
    "title": "fluorinated graphene / CFx-derived carbon; surface termination and hydrophobic carbon interface",
    "link": "https://www.nature.com/articles/s41565-019-0582-z"
  },
  "P/S/Se 单掺或共掺碳": {
    "kind": "文献线索",
    "venue": "Advanced Energy Materials / ACS Catalysis 等",
    "year": "近年",
    "title": "P, S, Se doped carbon for two-electron ORR and H2O2 electrosynthesis",
    "link": ""
  },
  "C2N / crystalline carbon nitride holey 2D framework": {
    "kind": "文献",
    "venue": "Nature Communications",
    "year": "2015",
    "title": "A two-dimensional porous crystalline carbon nitride",
    "link": "https://www.nature.com/articles/ncomms7486"
  },
  "金属单原子低 4e 倾向：Zn/Sn/Bi-N-C 等": {
    "kind": "文献线索",
    "venue": "Nature Catalysis / JACS / ACS Catalysis 等",
    "year": "近年",
    "title": "Zn-N-C, Sn-N-C, Bi-N-C single-atom catalysts for two-electron ORR",
    "link": ""
  },
  "高熵非金属共掺碳 B/N/O/F/S": {
    "kind": "文献线索",
    "venue": "Nature Reviews Materials / 高熵材料与碳催化文献",
    "year": "近年",
    "title": "high-entropy heteroatom-doped carbon for oxygen reduction and H2O2 electrosynthesis",
    "link": ""
  },
  "Graphene / h-BN in-plane 或垂直异质结": {
    "kind": "文献",
    "venue": "Nature Materials",
    "year": "2015",
    "title": "graphene / hexagonal boron nitride heterostructure article linked by Nature Materials source",
    "link": "https://www.nature.com/articles/nmat4349"
  },
  "Graphene / black phosphorus 或 phosphorene-carbon": {
    "kind": "文献",
    "venue": "Nature Nanotechnology",
    "year": "2014",
    "title": "Phosphorene: an unexplored 2D semiconductor with a high hole mobility",
    "link": "https://www.nature.com/articles/nnano.2014.257"
  },
  "MXene / carbon hybrid": {
    "kind": "综述/文献",
    "venue": "Nature Reviews Materials",
    "year": "2017",
    "title": "2D metal carbides and nitrides (MXenes) for energy storage",
    "link": "https://www.nature.com/articles/natrevmats201698"
  },
  "Carbon quantum dots / graphene quantum dots on CNT/graphene": {
    "kind": "文献",
    "venue": "Nature Communications",
    "year": "2012",
    "title": "Carbon dots for multiphoton bioimaging",
    "link": "https://www.nature.com/articles/ncomms1798"
  },
  "BDD / boron-doped diamond electrode": {
    "kind": "产品/公司页面",
    "venue": "CONDIAS",
    "year": "产品页",
    "title": "Boron-doped diamond electrodes",
    "link": "https://www.condias.de/en/products/boron-doped-diamond-electrodes/"
  },
  "商用 graphene nanotubes / SWCNT 网络": {
    "kind": "产品/公司页面",
    "venue": "OCSiAl",
    "year": "产品页",
    "title": "TUBALL graphene nanotubes",
    "link": "https://ocsial.com/tuball/"
  },
  "商用 graphene nanoplatelets / PureGRAPH / NanoXplore": {
    "kind": "产品/公司页面",
    "venue": "First Graphene / NanoXplore",
    "year": "产品页",
    "title": "PureGRAPH and industrial graphene products",
    "link": "https://firstgraphene.net/products/puregraph/"
  },
  "AvCarb / 碳纸 / GDL 结构电极": {
    "kind": "产品/公司页面",
    "venue": "AvCarb",
    "year": "产品页",
    "title": "Carbon papers and gas diffusion layers",
    "link": "https://www.avcarb.com/products/"
  },
  "体相六方金刚石 / bulk lonsdaleite": {
    "kind": "文献",
    "venue": "Nature",
    "year": "2026",
    "title": "Bulk hexagonal diamond",
    "link": "https://www.nature.com/search?q=%22Bulk%20hexagonal%20diamond%22"
  },
  "半-Mobius 碳环 / half-Mobius cyclocarbon topology": {
    "kind": "报道/实验室新闻",
    "venue": "University of Oxford Department of Chemistry",
    "year": "2026",
    "title": "A molecule with half-Mobius topology",
    "link": "https://www.chem.ox.ac.uk/article/a-molecule-with-half-mobius-topology"
  },
  "Biofilm-disrupting and redox-active carbon dots modulate Wnt/β-catenin signaling to resolve a...": {
    "kind": "文献",
    "venue": "Journal of Materials Science &amp; Technology",
    "year": "2027",
    "title": "Biofilm-disrupting and redox-active carbon dots modulate Wnt/β-catenin signaling to resolve acute bacterial inflammation",
    "link": "https://doi.org/10.1016/j.jmst.2026.05.043"
  },
  "Dual role of carbon nonstoichiometry in tuning dislocation behavior in high-entropy transitio...": {
    "kind": "文献",
    "venue": "Journal of Materials Science &amp; Technology",
    "year": "2027",
    "title": "Dual role of carbon nonstoichiometry in tuning dislocation behavior in high-entropy transition metal carbide ceramics",
    "link": "https://doi.org/10.1016/j.jmst.2026.06.012"
  }
};
